<?php

namespace MalekBundle\Repository;

/**
 * PubliciteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PubliciteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findPubliciteDQL()
    {
        $query=$this->getEntityManager()->createQuery(" SELECT e from MalekBundle:publicite e ORDER by e.priorite ASC ")->setMaxResults(4);

        return $query->getResult();
    }


}
