<?php

namespace IhebBundle\Controller;
use AppBundle\Entity\User;
use IhebBundle\Entity\Club;
use IhebBundle\Entity\News;
use IhebBundle\Entity\Notification;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

class NewsController extends Controller
{
    public function newNewAction(Request $request,$id)
    {
        $user = $this->container->get('security.token_storage')->getToken()->getUser();
        if ($user == null || empty($user) || $user == "anon.") {
            return $this->redirectToRoute('fos_user_security_login');
        } else {
            $id_user = $user->getId();
            $currentUser = $this->getDoctrine()->getRepository(User::class)->find($id_user);
            $club= $this->getDoctrine()->getRepository(Club::class)->find($id);
            $new = new News();
            if ($request->getMethod() == "POST") {

                $filephoto = $request->files->get('form_photo');
                $fileNamephoto = $this->generateUniqueFileName() . '.' . $filephoto->guessExtension();
                $filephoto->move($this->getParameter('brochures_directory'), $fileNamephoto);
                $new->setPhotoNews($fileNamephoto);
                $new->setIdClub($club);
                $new->setCreationDate(new \DateTime());
                $new->setTitle($request->get('form_title'));
                $new->setDescription($request->get('form_description'));

                $notif = new  Notification();
                $notif->setStatus(0);
                $notif->setSubject("New");
                $notif->setText($currentUser->getUsername()." adds a new named ".$club->getNameClub());

                foreach ($this->getDoctrine()->getRepository(User::class)->findAll() as $user){
                    if(in_array('ROLE_ADMIN', $user->getRoles())){
                        $notif->setIdUser($user);
                    }
                }

                $em = $this->getDoctrine()->getManager();
                $em->persist($new);
                $em->flush();

                $em1 = $this->getDoctrine()->getManager();
                $em1->persist($notif);
                $em1->flush();

                return $this->redirectToRoute('club_by_user');
            }

        }
        return $this->render('@Iheb/News/newNews.html.twig');

    }
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    public function getAllNewsAction(Request $request){
        if ($request->getMethod() == "POST") {
            $newRequest = $request->get('new_search');
            $listnews = $this->getDoctrine()->getRepository(News::class)->createQueryBuilder('c')
                ->where("c.title LIKE '%$newRequest%'")
                ->getQuery()->getResult();

        } else {
            $listnews = $this->getDoctrine()->getRepository(News::class)->findAll();
        }
        if (empty($listnews)) {
            $this->get('session')->getFlashBag()->add('notice', 'no new found !');
        }
        return $this->render('@Iheb/News/allNews.html.twig', array('news' => $listnews));
    }

    public function getNewsByClubAction(Request $request,$id){
        $club= $this->getDoctrine()->getRepository(Club::class)->find($id);
        if ($request->getMethod() == "POST") {
            $newRequest = $request->get('new_search');
            $listnews = $this->getDoctrine()->getRepository(News::class)->createQueryBuilder('c')
                ->where("c.title LIKE '%$newRequest%'")
                ->getQuery()->getResult();

        } else {
            $listnews = $this->getDoctrine()->getRepository(News::class)->findBy(array('idClub' => $club));
        }
        if (empty($listnews)) {
            $this->get('session')->getFlashBag()->add('notice', 'no new found !');
        }
        return $this->render('@Iheb/News/allNewsByClub.html.twig', array('news' => $listnews,'club'=>$club));
    }

}