koussay_comment:
    resource: "@KoussayBundle/Controller/CommentController.php"
    type:     annotation

koussay_event:
    resource: "@KoussayBundle/Controller/EventController.php"
    type:     annotation

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

chayma:
    resource: "@ChaymaBundle/Resources/config/routing.yml"
    prefix:   /chayma

malek:
    resource: "@MalekBundle/Resources/config/routing.yml"
    prefix:   /malek

koussay:
    resource: "@KoussayBundle/Resources/config/routing.yml"
    prefix:   /koussay

iheb:
    resource: "@IhebBundle/Resources/config/routing.yml"
    prefix:   /iheb

dorra:
    resource: "@DorraBundle/Resources/config/routing.yml"
    prefix:   /dorra

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
