<<<<<<< HEAD
malek_promotion:
    resource: "@MalekBundle/Controller/promotionController.php"
    type:     annotation

malek_sms:
    resource: "@MalekBundle/Controller/SMSController.php"
    type:     annotation

malek_email:
    resource: "@MalekBundle/Controller/EmailController.php"
    type:     annotation

malek_email:
    resource: "@MalekBundle/Controller/EmailController.php"
    type:     annotation

malek_publicite:
    resource: "@MalekBundle/Controller/PubliciteController.php"
=======
dorra_produit:
    resource: "@DorraBundle/Controller/ProduitController.php"
    type:     annotation

dorra_ressource:
    resource: "@DorraBundle/Controller/RessourceController.php"
    type:     annotation

dorra_ressource:
    resource: "@DorraBundle/Controller/RessourceController.php"
    type:     annotation

dorra_ressource:
    resource: "@DorraBundle/Controller/RessourceController.php"
    type:     annotation

dorra_ressource:
    resource: "@DorraBundle/Controller/RessourceController.php"
    type:     annotation

dorra_ressource:
    resource: "@DorraBundle/Controller/RessourceController.php"
>>>>>>> 6b7a62fdfb9b605c66c6eeaa2a0028cebbe702d5
    type:     annotation

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /back

chayma:
    resource: "@ChaymaBundle/Resources/config/routing.yml"
    prefix:   /chayma

malek:
    resource: "@MalekBundle/Resources/config/routing.yml"
    prefix:   /malek

koussay:
    resource: "@KoussayBundle/Resources/config/routing.yml"
    prefix:   /koussay

iheb:
    resource: "@IhebBundle/Resources/config/routing.yml"
    prefix:   /iheb

dorra:
    resource: "@DorraBundle/Resources/config/routing.yml"
    prefix:   /dorra

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


