<?php

namespace DorraBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEventDQL($dateD, $RS)
    {
        $query=$this->getEntityManager()->createQuery(" SELECT e from KoussayBundle:Event e WHERE e.date = :dateD and e.ressource = :RS ")
            ->setParameter('dateD',$dateD ) ->setParameter('RS',$RS ) ;
        return $query->getResult();
    }
    public function findDemandeDQL($dateD)
    {
        $query=$this->getEntityManager()->createQuery(" SELECT e from DorraBundle:Demande e WHERE e.dateD = :dateD  ")
            ->setParameter('dateD',$dateD )  ;
        return $query->getResult();
    }
    public function AccepterDemandeDQL($id)
    {
        $query=$this->getEntityManager()->createQuery(" UPDATE DorraBundle:Demande d set d.etat='Accepte' WHERE d.id= :id ")
            ->setParameter('id',$id )  ;
        return $query->getResult();
    }
    public function AjouterEventRsDQL($Id_RS, $Id_Event)
    {
        $query=$this->getEntityManager()->createQuery(" UPDATE KoussayBundle:Event d set d.ressource= :Id_RS WHERE d.id= :Id_Event")
            ->setParameter('Id_RS',$Id_RS )
            ->setParameter('Id_Event',$Id_Event ) ;
        return $query->getResult();
    }

}
